### PR TITLE
Fix combining a legacy mempool ddust tx

### LINKED ISSUE #7: Only create RPC client once
We currently create the RPC client in three different places. It should just be done once and passed around where needed.

### PR DESCRIPTION
**Pull request by bubb1es71**
While testing I found that I could not combine a ddust tx in the mempool if the input was a legacy script type (p2pkh). This PR fixes that issue. I also fixed the required RBF fee increase threshold from 1 sats/vb to 0.1 sats/vb.

While testing I added some new Justfile recipes and added a start_height when adding a new descriptor. Using a recent start height makes syncing much quicker for networks other than regtest. 

Finally I did the cleanup that fixes #7 while I was at it.

### CODE REVIEW

**Comment by bubb1es71** [comment]
Signet example Tx that combines a two input legacy (p2pkh) input ddust tx from the mempool with a new segwit (p2wpkh) ddust input. You can tell this tx started with the legacy input because the OP_RETURN message is empty. If it'd started with the segwit input the OP_RETURN would be "ash". 

You can also see the fee rate of this ddust tx went from 3.47 sat/vB with only the two legacy inputs to 4.27 sat/vB with the addition of the segwit dust input.

https://mempool.space/signet/tx/81354c442a0befc876e7504ba78b4e6f2f717f7d07774b18cdfcc885b5865090

File: src/main.rs [hunk 1]
```diff
@@ -69,9 +72,12 @@ fn main() {
                 if let (Some(mut wallet), mut store) =
                     load_wallet(db.clone(), network, wallet_name.clone())
                 {
-                    sync_wallet(&url, &auth, &mut wallet, &mut store);
+                    sync_wallet(&rpc_client, &mut wallet, &mut store);
                     wallet.list_unspent().for_each(|out| {
-                        if !out.is_spent && out.txout.value <= dust_amount {
+                        if !out.is_spent
+                            && out.txout.value <= dust_amount
+                            && out.chain_position.is_confirmed()
```
Comment (harismuzaffer) [inline src/main.rs]: While this ensures that only confirmed dust UTXOs are combined, this prevents spending unconfirmed dust UTXOs(without combining).

**Comment by harismuzaffer** [comment]
In the PR description, please fix the typo. It should be p2pkh instead of p2wpkh
